### ISSUE TITLE
Define the structure of a Schema with a json-schema.org

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#134]
A _Schema_ makes it possible for Try WordPress to be able to work with any type of source data (from hereon referred to as _Subject_, e.g. blog post, page, product, etc), **without requiring any changes to the code**. Adding support for a new _Subject_ type should be a matter of just supplying a new _Schema_ for that subject type.

A _Schema_ is a JSON file that exists under the `schemas/` directory at the root of the repo. The schema of a blog post would look something like the following:

> Note that more complex field types will exist in the future, like `array`. For the time being those are not being considered.

```json
// ./schemas/blog-post.json
{
    "title": "Blog Post",
    "postType": "post"
    "fields": {
        "title": {
            "type": "text"
        },
        "date": {
            "type": "date"
        },
        "content": {
            "type": "html"
        }
    }
}
```

Additionally, there is a [JSON Schema](https://json-schema.org/) that specifies the format of the JSON file of a  _Schema_.

There should be a script that validates all schemas under `schemas/` using the JSON Schema. The script must also validate that there are no two schemas with the same `postType`.

**Comment by psrpinto** [comment]
In #132 I suggested using the following format:

```json
// ./src/schemas/blog-post.json
{
    "title": "Blog Post",
    "fields": {
        "title": {
            "type": "text"
        },
        "date": {
            "type": "date"
        },
        "content": {
            "type": "html"
        }
    }
}
```

In https://github.com/WordPress/try-wordpress/discussions/101 and https://github.com/WordPress/try-wordpress/pull/132#issuecomment-2519588819 @akirk suggests using the following format instead:

> To be clear, the difference is that in Alex's version all schemas should be in a single file.


```json
// ./src/schemas/schemas.json
{
	"post": {
		"date": "Date",
		"author": "String",
		"title": "String",
		"content": "String",
	},
	"page": {
		"title": "String",
		"content": "String",
	}
}
```

@akirk If it still is the case that you consider having all schemas in the same file to be a superior option, could you please provide some context on why that is the case? Thank you.

**Comment by akirk** [comment]
Yes, for the moment I consider having one file the superior option. If it's just one file, that one file needs to be loaded and synced.

If they are split into multiple files you need a mechanism to identify them. In JavaScript you cannot glob a directory. It needs to be manually added to another include file.

My example needs to be extended further, taking some references from you:
```json
// ./src/schemas/schemas.json
{
	"post": {
		"title": "Blog Post",
		"fields": {
			"date": "Date",
			"author": "String",
			"title": "String",
			"content": "String",
		},
	},
	"page": {
		"title": "Page",
		"fields": {
			"title": "String",
			"content": "String",
		},
	}
}
```

**Comment by psrpinto** [comment]
After discussion, we have decided to split each schema into its own file, which will get built into a single file in #144

**Comment by psrpinto** [comment]
@akirk @ashfame I took the liberty of editing the description of this issue to reflect the solution we arrived at after discussion. Please take a look at the issue description and let me know if you have any feedback.

I will start work on this now in #145.

**Comment by akirk** [comment]
Looks great, thank you!
