### ISSUE TITLE
Load a Schema using JavaScript

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#135]
In #134 we have defined the structure of a _Schema_. We now need a way to load a schema into JavaScript code.

Probably something along these lines:

```ts
export function getSchema( subjectType: SubjectType ): object
```

Ideally we should find a way to automatically embed the schemas of all subject types, without needing to manually import a file when a new schema is added. In short, we **do not** want to do this:

```ts
import BlogPostSchema from './blog-post.json';
```

Instead, all schema files need to be automatically embedded into the bundle (e.g. through webpack).

**Comment by akirk** [comment]
We'll use the build process from #144 here.
