### ISSUE TITLE
Use Schemas to make backend generic

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#138]
Backend code should leverage the _Schema_ format defined in #134 so that a new _Schema_ can be added without requiring **any changes** to the code.

**Comment by psrpinto** [comment]
Currently we have different APIs for different subjects (`/blog-posts`, `/pages`, etc). However, the structure of all subjects is the same:

- id
- type (`blog-post`, `page`, etc).
- sourceUrl
- array of fields

For this reason, I think it would make sense to design the API in a generic way, where there is only a `/subjects` endpoint, as opposed to `/blog-posts`, `/pages`, etc).

The data can also be stored in a generic way, it's an array of fields and all fields have the same structure:

- name (`string`)
- rawValue (`string`): the "raw" HTML
- parsedValue (`string`): the result of running `rawValue` through our parser. The format will differ according to `type`, but it's always a string. If a complex object is needed, it will be serialized.

**Comment by psrpinto** [comment]
I think that some of us might have in mind that each subject type would correspond to a different post type. Given that all subject types have the same structure (see comment above), I would argue that they can be stored in as a single post type. I think this would greatly simplify things (we don't need to wrangle post types according to the schema, we just save whatever the API receives without caring which type it is). They all get saved in the same way, as post type `trywp_subject` (or similar).

@akirk @ashfame  If you think that each subject should have its own post type, could you please elaborate here on why that is? What makes that solution superior to having a single `trywp_subject` post type? Thank you.

**Comment by ashfame** [comment]
It's only the transformed output that could/would be different. Storing raw data is already saved as a single post type which is `liberated_data` post type, which I think is what you mean by `trywp_subject`, right?

**Comment by psrpinto** [comment]
Ok, thanks for confirming. That is indeed what I meant. I was under the impression that was not the case at the moment. Thank you for clarifying.

**Comment by akirk** [comment]
We worked on some prototype/pseudo code for this which can be the basis for this: https://gist.github.com/akirk/226c85e05a32969ca5099326248329bf

**Comment by ashfame** [comment]
Once #152 can finalize the design, this issue would be about implementation.
