### ISSUE TITLE
Schema: `required` attribute might be unnecessary

### ISSUE THREAD

**Issue by ashfame** [WordPress/try-wordpress#162]
When we save a subject while defining its blueprint, we save it completely empty (just its `sourceUrl`). So not only enforcing "required" attribute would be a problem, but it's unnecessary? Why do we need it? Is there an issue with the behavior of operating with whatever data we have as is?

**Comment by psrpinto** [comment]
I think it would be useful to have a `required` attribute because, for example, pages might not have a title. #157 is related to this.

**Comment by ashfame** [comment]
I understand the desire for data validation, but I am concerned about implementing a `required` attribute in this context.

The `required` attribute's purpose is to enforce mandatory fields, but for our use case, we would often encounter valid pages with varying data structures. For instance:
- Many modern landing pages intentionally omit visible titles for design reasons
- Several blogs deliberately hide publication dates for evergreen content
- Content structure varies significantly across different types of pages

Instead of enforcing specific required fields, I suggest we maintain flexibility by treating all fields as optional and working with whatever data is available. This approach would be more resilient to the diverse nature of web content.

Could you elaborate on the specific use cases where you feel required fields would be beneficial?

**Comment by psrpinto** [comment]
Good points @ashfame. I'm in favor of removing the `required` attribute from the schema, and adapting the code accordingly. Assigning this ticket to myself.
