### ISSUE TITLE
Can't find subject by source URL when calling the API

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#172]
```
### Create blog post
POST http://localhost:8888/wp-json/index.php?rest_route=/try-wp/v1/subjects/blog-post
Content-Type: application/json

{
    "sourceUrl": "https://foo"
}
###

### Find blog post by sourceUrl
GET http://localhost:8888/wp-json/index.php?rest_route=/try-wp/v1/subjects/blog-post?sourceurl=https://foo
Content-Type: application/json
###
```

The second request returns:

```json
{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method.",
    "data": {
        "status": 404
    }
}
```

**Comment by psrpinto** [comment]
Currently we're not url-encoding the value of `sourceurl`, but I also tried it after having modified the code so that `sourceurl` is url-encoded, but got the same result.

I briefly looked into what the problem could be but wasn't able to figure it out yet.

/cc @ashfame

**Comment by ashfame** [comment]
@psrpinto here's the correct url - http://localhost:8888/index.php?rest_route=/try-wp/v1/subjects/blog-post&sourceurl=https://foo

**Comment by psrpinto** [comment]
🤦 Of course, we need to use `&` because there's already a `?`. Thanks!
