### ISSUE TITLE
Preload playground when the extension starts

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#22]
We should already load playground in the background as the app starts so that in the optimum case the user never sees the playground loading screen.

**Comment by psrpinto** [comment]
I'm not sure we can do this because we don't know which "session" the user will open. I think we should close this in favour of making playground load faster (e.g. through #79).

Thoughts @ashfame ?

**Comment by ashfame** [comment]
@psrpinto I guess depends on the speed of "Fresh setup" vs "resetting" of playground? With all local files (when WP + PG is bundled in extension itself), it's likely the diff would only come to execution, so not much. But when not bundled, I imagine resetting would be quite faster than a fresh setup?

**Comment by ashfame** [comment]
Also #79 is for reliability of PG & its client to be in sync, not sure if there is a "speed" angle to it as well?

**Comment by psrpinto** [comment]
Just to be clear, what I was suggesting was that we close this issue because we can't possibly know which session (aka playground slug) the user would want to load, and we need to know the slug before booting playground, so that we can pass it to Playground.

Given we cannot do what this issue suggests, we can address the problem in a different way, by making Playground load faster (the root of this issue is that Playground is "slow" so the user needs to wait for it to boot).

#79 would make it faster because playground and all the assets it needs (e.g. wp.zip) would be fetched from the extension itself, which would likely be much faster than fetching it over the network.

So I would just close this issue, we could revisit this in the future if users ask for faster loads.

**Comment by psrpinto** [comment]
Sorry, #79 is not the issue I was thinking, I thought it was about bundling playground, but there is currently no issue for that.

**Comment by ashfame** [comment]
Right, I made my comment considering a future where playground is still not bundled, in which case booting it up, even though we would likely reset it, might provide faster access to a PG instance since all network calls are already done at that point.

Right now, PG also always load a temporary playground even though it has a saved one.

So, this issue will be relevant (we can close now, and re-open later) if we decide not to bundle PG along with the extension.

**Comment by psrpinto** [comment]
Ok, closing this one for now. 

> Right now, PG also always load a temporary playground even though it has a saved one.

I wasn't aware of this, should we open an issue?

**Comment by ashfame** [comment]
> I wasn't aware of this, should we open an issue?

I was describing playground.wordpress.net behavior. Not an issue for us :)
