### ISSUE TITLE
Playground data is not persisted

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#43]
Reloading the extension, wipes all data.

How to reproduce:

1. Comment out [these lines](https://github.com/WordPress/try-wordpress/blob/trunk/src/ui/preview/Playground.tsx#L76-L78), so that we don't delete all posts. (This code will also need to be adapted because this currently deletes all posts, but this is not the cause of the issue).
2. `npm run start`
3. In the Admin tab, create a post
4. Navigate to the list of posts, in the Admin, and verify that the post is there
5. Reload the extension through the browser developer tools (Cmd+R when the developer tools window is in focus)
6. Navigate to the list of posts, in the Admin.
7. The post that was created in 3. is not listed in the list of posts

**Comment by Felipe-Rafael-Rosa** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by psrpinto** [comment]
The way we set up Playground is as follows.

We create an iframe with an empty `src`:

```html
<iframe src='' id="playground"/>
```

Then we call `startPlaygroundWeb()`:

```ts
const client: PlaygroundClient = await startPlaygroundWeb( {
    iframe: document.getElementById( 'playground' ),
    siteSlug: 'foo',
    remoteUrl: 'https://playground.wordpress.net/remote.html?storage=browser'
} );
```

But I'm not sure this is the correct way to set the storage type. I noticed that at playground.wordpress.net, when the storage is set to `browser`, it doesn't pass `storage=browser` as a query param to `remote.html`.

I'm currently trying to figure out if there's another way to set the storage type, when using `startPlaygroundWeb()`.

**Comment by adamziel** [comment]
The `mounts` option of `startPlaygroundWeb` is the way to go here. For example:

```ts
await startPlaygroundWeb( {
	mounts: [
		{
			device: {
				type: 'opfs',
				path: '/data-liberation-site-15',
			},
			mountpoint: '/wordpress',
		}
	]
} );
```

You may also run into issues with [Storage Partitioning](https://developers.google.com/privacy-sandbox/cookies/storage-partitioning) – LMK if that happens.

> I noticed that at playground.wordpress.net, when the storage is set to browser, it doesn't pass storage=browser as a query param to remote.html.

That's expected, Playground is now using the Comlink API to pass these values. Did the query param come from a documentation page? If yes, that page is outdated.
