### ISSUE TITLE
Store HTML of entire page being liberated

### ISSUE THREAD

**Issue by ashfame** [WordPress/try-wordpress#64]
We should not just store the entire HTML of a HTML page, but also the user selection of each element they made in the UI, to provide the same context of user selection when re-running transformations.

**Comment by ashfame** [comment]
I would like to propose the idea of storing HTML as the base layer of liberating data. The goal of data liberation can be fully described in a 2 step process:

1) Being able to gather the needed date
2) Transforming the obtained data in WordPress constructs

If you think about what it means to liberate a website, it means being able to collect all the links (html pages) of the website, and handle them one by one:

- Ignore page
- Handle page; it becomes a `known` post_type
- Handle page; its not known what post_type would be used, so `unknown`

This enables us to actually track the progress of liberation as one is running (X of Y html pages done). This is also the mental model a user would have, how many of my P posts, Q pages and R products etc have been migrated over.

And clubbing this base layer with the idea of we ourselves re-running transformations with newer transformation logic or 3rd party plugins handling data afterwards, we have set ourselves a loss-less stage for building on top of this base layer without a hard requirement of supporting a list of subject types (think content types) and transformations on raw_data (literal html source) can be processed in an iterative manner.

Additionally, this also provides guard rails for the UX of our tool. In which, we can present strategies for processing data:

- Import blogpost (Current behavior that's already implemented)
- Import pages by using navigation (https://github.com/WordPress/try-wordpress/pull/103)
- Import pages manually (By specifying/visiting URL)
- Import products

With each strategy having executed, they come back to this same screen, which would now show how many subject_types (think P posts, Q pages etc) have been handled. And again present the strategies, they can choose another, or specify a page that got missed etc. to achieve (Y of Y html pages liberated).

So, this covers the basis of user being able to realize how many pages has been captured and what remains, choosing to re-run a different strategy next.

@psrpinto @akirk Do you guys conceptually agree on this path? Would love to hear your feedback on it.

**Comment by akirk** [comment]
I am not sure I understand exactly what you mean. I think it's reasonable to store the HTML of the page which is extracted from as a "backup."

One advantage of the extension is the availability of JS and the Gutenberg paste handler which can identify contained blocks. The `post_content` should contain the backup HTML, the metadata should contain ([see the discussion](https://github.com/WordPress/try-wordpress/discussions/101)) the parsed content (with Gutenberg's paste handler) as `post_content` meta field when it is a post or page.

I hope that the standard can be that the php plugin doesn't need to do any parsing and can just use the extracted metadata.

Are you suggesting something different?

**Comment by ashfame** [comment]
This proposal only offers a conceptual perspective of looking at things. It's not different from what we are doing today. Here is another example that would hopefully make it clear:

Treating storage of just raw html as base layer implies, the data liberation tool (Extension + WP plugin) can just copy over the raw html and nothing else (literally no transformations - which in our case is the paste_handler from Gutenberg for now)  in version 0.0.1 and we can still handle all transformations later on, with a newer version of Try-WP WordPress plugin working with just raw html data that we have already copied over.

I know extension lets us provide the user interaction element, but forget about that for a moment. Let's just treat the transformation logic as a single black box that can just produce output on the basis of input provided.

Now, in version 0.0.2, we can add support for blogposts, and process them all from raw html (base layer).
In version 0.0.3, we can add support for products and process them all from raw html (base layer).

So, in principle, we are not limited by what we can do today (transformation logic), because we have the base layer to always run transformations over and over.

In practice, we are already running some transformations, but with base layer in place and treated as first-class citizen, we are able to make sense of the re-running transformations situation much better.

**Comment by psrpinto** [comment]
I'm not sure I fully understand what you are proposing. If I understood correctly, the idea would be that the extraction of the raw HTML from the source site, and the parsing of said HTML into a `parsedValue` would be done at different points in time?

In other words, it should be possible to call the API endpoint with just the `raw` HTML without supplying the `parsedValue`, and the `parsedValue` could be calculated at a different time in the future?

**Comment by ashfame** [comment]
@psrpinto Yes, exactly that! It's just a mental model encapsulating the entire approach in very simple terms and give us a direction around which we can build our UX of the tool.

> the idea would be that the extraction of the raw HTML from the source site, and the parsing of said HTML into a parsedValue would be done at different points in time

*could* be but we don't need to, as is the case right now.

**Comment by psrpinto** [comment]
I see, I agree it makes sense to have that mental model in mind. At the moment we're always passing the `parsedValue` along with the `raw` value, but in the future if we encounter use cases that should split the extraction from the parser, we can make it happen.
